spring:
  application:
    name: microservice-A

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.autoconfigure: DEBUG

---

spring:
  config:
    activate:
      on-profile: sit1
    import:
      - "configserver:"
  cloud:
    config:
      enabled: true
      fail-fast: true
      uri: http://localhost:8888/config-server

---
spring:
  config:
    activate:
      on-profile: sit2
    import:
      - "configserver:"
  cloud:
    config:
      enabled: true
      fail-fast: true
      uri: http://localhost:8888/config-server